- name: Add nginx repo key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name:  Get nginx repositorie deb
  shell: |
    echo "deb http://nginx.org/packages/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) nginx"
  register: debString

- name:  Get nginx repositorie deb-src
  shell: |
    echo "deb http://nginx.org/packages/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) nginx"
  register: debStringSrc

- name: Add nginx repo in /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{debString.stdout}}"

- name: Add nginx repo in /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{debStringSrc.stdout}}"

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes

- name: Create nginx Config
  template:
    src: nginx.conf.tmpl
    dest: /etc/nginx/nginx.conf

- name: Delete default page
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: yes
