- name: Get Helm tiller deploy files
  get_url:
    url: https://git.io/get_helm.sh
    dest: /opt/config/helm.sh
  become: true

- name: Change helm.sh access setings
  file:
    path: /opt/config/helm.sh
    mode: '700'
  become: true

- name: Install helm
  shell: |
     ./helm.sh
  args:
    chdir: /opt/config
  become: true

- name: Create Helm rbac config files
  template:
    src: rbac-config.yaml.tmpl
    dest: /opt/config/rbac-config.yaml
  become: true

- name: Init Helm server
  shell: |
    kubectl apply -f rbac-config.yaml && \
    helm init --service-account tiller
  args:
    chdir: /opt/config
