---
# Install Kubernetes
- name: Install containerd
  hosts: [kube_workers, kube_ingress]
  become: yes
  become_method: sudo

  tasks:
    - name: set sysctl
      sysctl:
        name: "{{ item }}"
        value: "1"
      loop:
        - net.ipv4.ip_forward
      tags:
        - kubelet

    - name: Install kubernetes
      include_role:
        name: "{{ item }}"
      with_items:
      - kubelet
      tags:
        - kubelet


# Install containerd
- name: Install containerd
  hosts: [kube_workers, kube_ingress]
  become: yes
  become_method: sudo

  tasks:
    - name: inatsll containerd
      include_role:
        name: containerd
      tags:
        - containerd


- name: Crettae workers
  hosts: [kube_workers, kube_ingress]
  become: yes
  become_method: sudo

  tasks:
    - name: Reset Old Cluster
      shell: |
        kubeadm reset --force
      tags: kube_workers

    - name: Init all workers
      include_role:
        name: kube_workers
      tags: kube_workers


- name: Create haproxy
  hosts: [kube_workers, kube_ingress]
  become: yes
  become_method: sudo

  tasks:
    - name: haproxy
      include_role:
        name: haproxy
      tags: haproxy