
- name: reset kubernetes  cluster
  hosts: [kube_ingress, kube_workers]
  become: yes
  become_method: sudo
  gather_facts: no


  tasks:
    - name: deploy ntp and tzdata packages
      apt:
        name: ['ntp', 'tzdata']
        update_cache: true
      become: true

    - name: restart ntp service
      ansible.builtin.systemd_service:
        state: restarted
        name: ntp
      

