- name: Install ingress controller
  hosts: master1
  gather_facts: no

  vars:
    HOST_COUNT: "{{ groups['ingressnodes'] | length }}"

  tasks:
    - name: Install ingress controller
      include_role:
        name: ingress
