---
#Add directory for cert
- name: Add tmp directory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: create temp cert directory
      file:
        path: /tmp/k8s
        state: directory
        force: yes


# Installing Kubernetes
- name: Installing shared packages and Kubernetes for the masters and work nodes
  hosts: [masters, worknodes, ingressnodes ]
  become: yes
  become_method: sudo

  tasks:
    - name: Install kubernetes
      include_role:
        name: "{{ item }}"
      with_items:
      - kubelet
      tags: kubelet


#Installing CRI - conainerd or docker
- name: Installing Docker
  hosts: [masters, worknodes, ingressnodes]
  become: yes
  become_method: sudo

  tasks:
    - name: enable ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
      tags: docker

    - name: Install docker
      include_role:
        name: docker
      tags: docker


#Install the soft that is only needed on the masters
- name: Install ETCD
  hosts: masters
  become: yes
  become_method: sudo

  tasks:
    - name: Install etcd
      include_role:
        name: "{{ item }}"
      with_items:
      - etcd
      tags:
        - etcd
        - ssl