
#Add directory for cert
- name: Add tmp directory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: create temp cert directory
      file:
        path: /tmp/k8s
        state: directory
        force: yes

# Installing
- name: Installing shared packages and Kubernetes for the masters and work nodes
  hosts: masters
  become: yes
  become_method: sudo

  tasks:
    - name: Install kubernetes
      include_role:
        name: kubelet


- name: Installing CRI
  hosts: masters
  become: yes
  become_method: sudo

  tasks:
    - name: Install docker
      include_role:
        name: docker
      when: criType == "docker"

    - name: Install containerd
      include_role:
        name: containerd
      when: criType == "containerd"

- name: Setting Up kubernetes masters
  hosts: masters
  become: yes
  become_method: sudo

  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
      - etcd
      - keepalived

    - name: enable ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1

- name: Init first cluster master
  hosts: master1
  become: yes
  become_method: sudo

  tasks:
    - name: Reset Old Cluster and del docker containers
      shell: |
        kubeadm reset --force
      when: criType == "docker"

    - name: Reset Old Cluster and del crictl containers
      shell: |
        kubeadm reset --force --cri-socket /run/containerd/containerd.sock
      when: criType == "containerd"

    - name: Init First master {{ansible_hostname}}
      include_role:
        name: initMaster


    - name: Get file names to copy
      shell: |
        find /etc/kubernetes/pki -type f
      register: files_to_copy


    - name: Copy cert to ansiblehost
      fetch:
        src: "{{ item }}"
        dest: /tmp/k8s/
      with_items:
       - "{{ files_to_copy.stdout_lines }}"

    - name:  install Calico CIDR
      become_user: "{{ kubernetesUser }}"
      shell: |
        kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml && \
        kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
      args:
        executable: /bin/bash


- name: Init other masters
  hosts: master2:master3
  become: yes
  become_method: sudo

  tasks:
    - name: Reset Old Cluster and del docker containers
      shell: |
        kubeadm reset --force
      when: criType == "docker"

    - name: Reset Old Cluster and del crictl containers
      shell: |
        kubeadm reset --force --cri-socket /run/containerd/containerd.sock
      when: criType == "containerd"

    - name: Create PKI directory
      file:
        path: /etc/kubernetes/pki/
        state: directory
        group: root
        owner: root
        force: yes

    - name: copy certificate
      copy:
        src:  /tmp/k8s/master1/etc/kubernetes/pki/
        dest: /etc/kubernetes/pki/
      tags: test

    - name: init {{ansible_hostname}}
      include_role:
        name: initMaster
