- name: Installing shared packages for the masters and work nodes
  hosts: all
  become: yes
  become_method: sudo


  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
      - kubelet
      - containerd


- name: Setting Up kubernetes msters
  hosts: masters
  become: yes
  become_method: sudo

  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
      - etcd
      - keepalived

- name: Init first cluster master
  hosts: master1
  become: yes
  become_method: sudo

  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
      - initMaster
