- name: Installing shared packages for the masters and work nodes
  hosts: all
  become: yes
  become_method: sudo


  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
      - kubelet
      - containerd


- name: Setting Up kubernetes msters
  hosts: masters
  become: yes
  become_method: sudo

  vars:
    - etcdName1: "{{ hostvars[groups['masters'][0]]['ansible_hostname'] }}"
    - etcdName2: "{{ hostvars[groups['masters'][1]]['ansible_hostname'] }}"
    - etcdName3: "{{ hostvars[groups['masters'][2]]['ansible_hostname'] }}"


  tasks:
    - include_role:
        name: "{{ item }}"
      with_items:
      - etcd
      - keepalived
      - initMaster
