
# Installing Kubernetes
- name: Installing shared packages and Kubernetes for the masters and work nodes
  hosts: [masters, worknodes, ingressnodes ]
  become: yes
  become_method: sudo

  tasks:
    - name: Install kubernetes
      include_role:
        name: "{{ item }}"
      with_items:
      - kubelet


#Installing CRI - conainerd or docker
- name: Installing CRI
  hosts: [masters, worknodes, ingressnodes]
  become: yes
  become_method: sudo

  tasks:
    - name: enable ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1


    - name: Install docker
      include_role:
        name: docker
      when: criType == "docker"

    - name: Install containerd
      include_role:
        name: containerd
      when: criType == "containerd"



#Install the soft that is only needed on the masters
#- name: Setting Up kubernetes masters
#  hosts: masters
#  become: yes
#  become_method: sudo
#
#  tasks:
#    - name: Install etcd
#      include_role:
#        name: "{{ item }}"
#      with_items:
#      - etcd
#
#    - name: Install etcd
#      include_role:
#        name: "{{ item }}"
#      with_items:
#      - keepalived
      when: keepalived == "true"


    - name: Install nginx
      include_role:
        name: nginx
      when: apiLoadBalancer == "master"
