- name: del local certificate
  hosts: localhost

  tasks:
    - name:  del local certificate
      file:
        path: /tmp/k8s/
        state: absent


- name: reset kubernetes and etcd cluster
  hosts: [masters, worknodes]
  become: yes
  become_method: sudo

  tasks:
    - name: Purge nginx
      apt:
        name: nginx
        state: absent
      when:
        - inventory_hostname in groups['masters']
        - apiLoadBalancer == "true"
    - name: stop etcd
      systemd:
        name: etcd
        state: stopped
      when: inventory_hostname in groups['masters']

    - name: erase etcd database
      file:
        path: /var/lib/etcd/
        state: absent
      when: inventory_hostname in groups['masters']

    - name: Reset Kubernetes cluster and del all configs
      shell: |
        kubeadm reset --force

    - name: Reset Kubernetes cluster and del all configs (containerd)
      shell: |
        kubeadm reset --force --cri-socket /run/containerd/containerd.sock \
        && crictl stop $(crictl ps -a -q) \
        && crictl rm $(crictl ps -a -q)
      ignore_errors: yes


    - name: Purge docker
      apt:
        name: docker
        state: absent
      when:
        - inventory_hostname in groups['masters']
        - criType == "docker"
