- name: del local certificate
  hosts: localhost
  gather_facts: no

  tasks:
    - name:  del local certificate
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/k8s
        - /tmp/etcd/certs/


- name: reset kubernetes  cluster
  hosts: [kube_masters, kube_ingress, kube_workers]
  become: yes
  become_method: sudo
  gather_facts: no


  tasks:
    - name: Reset Kubernetes cluster
      shell: |
        kubeadm reset --force
      become: true
      ignore_errors: true

    - name: Purge kubeadm, kubelet, kubectl, and shared packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
        force: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - haproxy



- name: reset etcd cluster
  hosts: [kube_masters]
  become: yes
  become_method: sudo
  gather_facts: no

  vars:
    HOST_COUNT: "{{ groups['ingressnodes'] | length }}"

  tasks:
    - name: stop etcd
      systemd:
        name: etcd
        state: stopped
      when: inventory_hostname in groups['kube_masters']
      ignore_errors: true
      tags: etcd


    - name: erase etcd database
      file:
        path: /var/lib/etcd/
        state: absent
      when: inventory_hostname in groups['kube_masters']
      tags: etcd

    - name: Delete etcd
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /usr/local/bin/Documentation/
      - /usr/local/bin/etcd
      - /usr/local/bin/etcdctl
      - /usr/local/bin/README-etcdctl.md
      - /usr/local/bin/README.md
      - /usr/local/bin/READMEv2-etcdctl.md
      when:
        - inventory_hostname in groups['kube_masters']
      tags: etcd


    - name: delete cluster config
      file:
        path: "{{ item }}"
        state: absent
      loop:
      - /opt/config
