- name: del local certificate
  hosts: localhost

  tasks:
    - name:  del local certificate
      file:
        path: /var/lib/etcd
        state: absent


- name: reset kubernetes and etcd cluster
  hosts: masters
  become: yes
  become_method: sudo

  tasks:
    - name: stop etcd
      systemd:
        name: etcd
        state: stopped

    - name: erase etcd database
      file:
        path: /var/lib/etcd/
        state: absent


    - name: started etcd
      systemd:
        name: etcd
        state: started
