- name: del local certificate
  hosts: localhost
  gather_facts: no

  tasks:
    - name:  del local certificate
      file:
        path: /tmp/k8s/
        state: absent


- name: reset kubernetes and etcd cluster
  hosts: [k8s]
  become: yes
  become_method: sudo
  gather_facts: no

  vars:
    HOST_COUNT: "{{ groups['ingressnodes'] | length }}"

  tasks:
    - name: Reset Kubernetes cluster
      shell: |
        kubeadm reset --force
      become: true
      ignore_errors: true


    - name: Purge nginx
      apt:
        name: nginx
        state: absent
        purge: true
      when:
        - inventory_hostname in groups['kube_masters']
        - apiLoadBalancer == "true"
      ignore_errors: true


    - name: stop etcd
      systemd:
        name: etcd
        state: stopped
      when: inventory_hostname in groups['kube_masters']
      ignore_errors: true
      tags: etcd


    - name: erase etcd database
      file:
        path: /var/lib/etcd/
        state: absent
      when: inventory_hostname in groups['kube_masters']
      tags: etcd

    - name: Delete etcd
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /usr/local/bin/Documentation/
      - /usr/local/bin/etcd
      - /usr/local/bin/etcdctl
      - /usr/local/bin/README-etcdctl.md
      - /usr/local/bin/README.md
      - /usr/local/bin/READMEv2-etcdctl.md
      when:
        - inventory_hostname in groups['kube_masters']
      tags: etcd


    - name: Purge docker
      apt:
        name: docker
        state: absent
        purge: true
      when:
        - inventory_hostname in groups['kube_masters'] or inventory_hostname in groups['worknodes']

    - name: delete ingress config
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /opt/config/helm.sh
      - /opt/config/mandatory.yaml
      - /opt/config/service-nodeport.yaml


    - name: Purge kubeadm, kubelet, kubectl, and shared packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
        force: yes
      with_items:
      - kubelet
      - kubeadm
      - kubectl
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - haproxy
