- name: del local certificate
  hosts: localhost

  tasks:
    - name:  del local certificate
      file:
        path: /tmp/k8s/
        state: absent


- name: reset kubernetes and etcd cluster
  hosts: [masters, worknodes]
  become: yes
  become_method: sudo

  tasks:
    - name: Reset Kubernetes cluster
      shell: |
        kubeadm reset --force
      become: true

    - name: Del all pods (containerd)
      shell: |
        crictl stop $(crictl ps -a -q) && \
        crictl rm $(crictl ps -a -q)
      when: criType == "containerd"
      become: true

    - name: Purge nginx
      apt:
        name: nginx
        state: absent
        purge: true
      when:
        - inventory_hostname in groups['masters']
        - apiLoadBalancer == "true"

    - name: stop etcd
      systemd:
        name: etcd
        state: stopped
      when: inventory_hostname in groups['masters']

    - name: stop CRI containerd
      systemd:
        name: containerd
        state: stopped
      when:
        - inventory_hostname in groups['masters']
        -  criType == "containerd"

    - name: erase etcd database
      file:
        path: /var/lib/etcd/
        state: absent
      when: inventory_hostname in groups['masters']

    - name: Delete etcd
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /usr/local/bin/Documentation/
      - /usr/local/bin/etcd
      - /usr/local/bin/etcdctl
      - /usr/local/bin/README-etcdctl.md
      - /usr/local/bin/README.md
      - /usr/local/bin/READMEv2-etcdctl.md
      when:
        - inventory_hostname in groups['masters']
        - garbageCollection == "true"

    - name: Delete containerd
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /etc/systemd/system/containerd.service
      - /etc/crictl.yaml
      - /opt/containerd/
      - /usr/local/bin/containerd
      - /usr/local/bin/containerd-release
      - /usr/local/bin/containerd-shim
      - /usr/local/bin/containerd-stress
      - /usr/local/bin/crictl
      - /usr/local/bin/critest
      - /usr/local/bin/ctr
      when:
        - criType == "containerd"
        - inventory_hostname in groups['masters']
        - garbageCollection == "true"

    - name: Purge docker
      apt:
        name: docker
        state: absent
        purge: true
      when:
        - inventory_hostname in groups['masters'] or inventory_hostname in groups['worknodes']
        - criType == "docker"
