- name: Cluster info
  hosts: master1
  gather_facts: true

  vars:
    HOST_COUNT: "{{ groups['ingressnodes'] | length }}"


  tasks:
    - name: Get mandatory deployment
      get_url:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
        dest: /opt/config/mandatory.yaml
      when: ingressHA == "true"
      become: true

    - name: Change ingress deployment add replicas
      lineinfile:
        path: /opt/config/mandatory.yaml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '  replicas: 1', line: '  replicas: 3' }
        - { regexp: '  replicas: 1', line: '  replicas: 3' }
      when: ingressHA == "true"
      become: true

    - name: Add nodeSelector in ingress deployment
      lineinfile:
        path: /opt/config/mandatory.yaml
        insertafter: "{{ item.insertafter }}"
        line: "{{ item.line }}"
      with_items:
        - {insertafter: '            memory: 20Mi', line: "      nodeSelector:\n         nodeType: ingress"}
        - {insertafter: 'EOF', line: "      nodeSelector:\n         nodeType: ingress"}
      become: true
      when: ingressHA == "true"
