- name: Cluster info
  hosts: master1
  gather_facts: true

  vars:
    HOST_COUNT: "{{ groups['ingressnodes'] | length }}"


  tasks:
    - name: Get mandatory deployment
      debug:
        msg: "{{ HOST_COUNT }}"
      when: HOST_COUNT > "0"
