  - name: Create kube-proxy config file
    file:
      path: "{{ item }}"
      mode: 0777
      state: touch
    with_items:
      - /opt/config/kube-proxy.txt
      - /opt/config/kube-api-configmap.yaml
    become: yes


  - name: Get kube-proxy config
    shell: |
      kubectl get -n kube-system configmap/kube-proxy -o yaml > /opt/config/kube-api-configmap.yaml

  - name: Replace API server export
    replace:
      dest: /opt/config/kube-api-configmap.yaml
      regexp: '6443'
      replace: '16443'
    become: true

  - name: Reconfigure kube-proxy
    shell: |
      kubectl apply -f /opt/config/kube-api-configmap.yaml \ &&
      kubectl get pods --all-namespaces -o wide | grep proxy > /opt/config/kube-proxy.txt && \
      kubectl delete pod -n kube-system $(awk '{print $2}' /opt/config/kube-proxy.txt)

  - name: Create kube-proxy config file
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /config/kube-proxy.txt
    - /opt/config/kube-api-configmap.yaml
    become: yes
