- name: Reset Old Cluster
  shell: |
    kubeadm reset --force

- name: restart Keepalived
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - keepalived
    - etcd
    - kubelet


- name: Create kubeadm config directory
  file:
    path: /opt/config/kubeadm
    state: directory

- name: Config kubeadm-init.yaml
  template:
    src: kubeadm-init.yaml.tmpl
    dest: /opt/config/kubeadm/kubeadm-init.yaml

- name: pull k8s images
  shell: |
    kubeadm config images pull

- name: Create master node
  shell: |
    kubeadm init --config=kubeadm-init.yaml
  args:
    chdir: /opt/config/kubeadm/
