- name: restart Keepalived
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - keepalived
    - etcd
    - kubelet

- name: Create kubeadm config directory
  file:
    path: /opt/config/kubeadm
    state: directory

- name: Config kubeadm-init.yaml
  template:
    src: kubeadm-init.yaml.tmpl
    dest: /opt/config/kubeadm/kubeadm-init.yaml

- name: Add containerd criSocket to kubeadm-init.yaml
  lineinfile:
    path: /opt/config/kubeadm/kubeadm-init.yaml
    line: 'criSocket: /run/containerd/containerd.sock'
  when: criType == "containerd"

- name: pull kimages of k8s with the docker
  shell: |
    kubeadm config images pull
  when: criType == "docker"

- name: pull kimages of k8s with the crictl
  shell: |
    kubeadm config images pull --cri-socket-path /run/containerd/containerd.sock
  when: criType == "containerd"


- name: Create master node thih Docker
  shell: |
    kubeadm init --config=kubeadm-init.yaml
  args:
    chdir: /opt/config/kubeadm/
  when: criType == "docker"

- name: Create master node thih Containerd
  shell: |
    kubeadm init --config=kubeadm-init.yaml --skip-preflight-checks
  args:
    chdir: /opt/config/kubeadm/
  when: criType == "containerd"

- name: Add export KUBECONFIG=/etc/kubernetes/admin.conf to bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'

- name: Apply bashrc changes
  shell: |
    source /root/.bashrc
  args:
    executable: /bin/bash

- name: create kubernetes config directory
  become_user: "{{ kubernetesUser }}"
  file:
    path: ~/.kube/
    state: directory

- name: permissions for admin.conf
  file:
    path: /etc/kubernetes/admin.conf
    mode: 0775

- name: copy admin.conf to home directory
  become_user: "{{ kubernetesUser }}"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "~/.kube/config"
    owner: "{{ kubernetesUser }}"
    mode: 0755
    remote_src: True
