- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/archives

- name: Get etcd archive
  get_url:
    url: https://github.com/coreos/etcd/releases/download/{{etcd_version}}/etcd-{{etcd_version}}-linux-amd64.tar.gz
    dest: /opt/archives/etcd-{{etcd_version}}-linux-amd64.tar.gz

- name: Get and unpack etcd
  shell: |
    tar -xvf etcd-v3.1.17-linux-amd64.tar.gz -C /opt/test --strip-components=1
  args:
    chdir: /opt/archives

- name: Create systemd service for etcd
  template:
    src: etcd.service.vb.j2
    dest: "/etc/systemd/system/etcd.service"

- name: Create etcd env file
  template:
    src: etcd.env.tmpl
    dest: /etc/etcd.env

- name: Enable and start etc cluster
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes
