- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/archives


- name: Get and unpack etcd
  shell: |
    curl -sSL https://github.com/coreos/etcd/releases/download/{{etcd_version}}/etcd-{{etcd_version}}-linux-amd64.tar.gz \
    | tar -xzv --strip-components=1 -C /usr/local/bin/

- name: Create systemd service for etcd
  template:
    src: etcd.service.vb.j2
    dest: "/etc/systemd/system/etcd.service"

- name: Create etcd env file
  template:
    src: etcd.env.tmpl
    dest: /etc/etcd.env

- name: Enable and start etc cluster
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes
