
- name: Get mandatory deployment
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
    dest: /opt/config/mandatory.yaml
  become: true

- name:  change ingress replicas quantity if ingressnodes available
  lineinfile:
    path: /opt/config/mandatory.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '  replicas: 1', line: '  replicas:  {{HOST_COUNT}}' }
  when:  HOST_COUNT > "0"
  become: true



- name:  change ingress replicas quantity if ingressnodes not available
  lineinfile:
    path: /opt/config/mandatory.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '  replicas: 1', line: '  replicas: 3' }
  when:  HOST_COUNT < "1"
  become: true

- name: Add nodeSelector in ingress deployment
  lineinfile:
    path: /opt/config/mandatory.yaml
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  with_items:
    - {insertafter: '            memory: 20Mi', line: "      nodeSelector:\n         nodeType: ingress"}
    - {insertafter: 'EOF', line: "      nodeSelector:\n         nodeType: ingress"}
  become: true
  when:  HOST_COUNT > "0"


- name: Apply ingres controler deployment
  shell: |
    kubectl apply -f /opt/config/mandatory.yaml
  become: false


- name: copy service-nodeport
  template:
    src: service-nodeport.j2
    dest: /opt/config/service-nodeport.yaml
  become: true
  tags: test


- name: Apply ingress controller service
  shell: |
    kubectl apply -f service-nodeport.yaml
  args:
    chdir: /opt/config
  become: false
