- name: Installing keepalived
  apt:
   name: keepalived
   update_cache: true


- name: Check that the /keepalived.conf exists
  stat:
    path: /etc/keepalived/keepalived.conf
  register: conf_result


- name: Backup keepalived.conf
  copy:
    src: /etc/keepalived/keepalived.conf
    dest: /etc/keepalived/keepalived.conf.bak
    remote_src: true
  when: conf_result.stat.exists == True


- name: Config keepalived.conf
  template:
    src: keepalived.conf.tmpl
    dest: /etc/keepalived/keepalived.conf


- name: Upload the keepalived test script
  template:
    src: check_apiserver.sh.tmpl
    dest: /etc/keepalived/check_apiserver.sh


- name: Enable and start keppalived VRRP
  systemd:
    name: keepalived
    state: started
    enabled: yes
