- name: Preinstall packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'curl', 'gnupg2']
    update_cache: yes
  tags: docker
    

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags: docker

- name: Remove a Apt specific signing key
  apt_key:
    id: 0EBFCD88
    state: present
  tags: docker

- name:  Get docker repositorie
  shell: |
    echo "deb [arch=amd64] https://download.docker.com/linux/debian  $(lsb_release -cs) stable"
  register: debString
  tags: docker


- name: Add docker repo in /etc/apt/sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{debString.stdout}}"
  tags: docker

- name: Update apt cache
  apt:
    update_cache: yes
  tags: docker


- name: Installing docker
  apt:
    name: ['docker-ce={{ dockerVersion }}', 'docker-ce-cli={{ dockerVersion }}', 'containerd.io']
  tags: docker



- name: Set up the Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
  tags: docker
  when: "'kube_workers' in group_names"

